// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCconMBlndNYs4VopfR-xCppNPbctlu_0I',
    appId: '1:745267793428:web:83f39c060a2fcb3b67e101',
    messagingSenderId: '745267793428',
    projectId: 'prakflutterfirebase-8f942',
    authDomain: 'prakflutterfirebase-8f942.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-8f942.appspot.com',
    measurementId: 'G-CXHCFHRF9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARhaaAC4SPzWjbTmeDVrT5RNpQ_jjk6cI',
    appId: '1:745267793428:android:a7c7362123dba1ca67e101',
    messagingSenderId: '745267793428',
    projectId: 'prakflutterfirebase-8f942',
    storageBucket: 'prakflutterfirebase-8f942.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGNavCi-nVxVPcJbBFyyEVwFLWrBjIGkc',
    appId: '1:745267793428:ios:3eb858137d594ac267e101',
    messagingSenderId: '745267793428',
    projectId: 'prakflutterfirebase-8f942',
    storageBucket: 'prakflutterfirebase-8f942.appspot.com',
    iosBundleId: 'com.example.praktikum9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGNavCi-nVxVPcJbBFyyEVwFLWrBjIGkc',
    appId: '1:745267793428:ios:3eb858137d594ac267e101',
    messagingSenderId: '745267793428',
    projectId: 'prakflutterfirebase-8f942',
    storageBucket: 'prakflutterfirebase-8f942.appspot.com',
    iosBundleId: 'com.example.praktikum9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCconMBlndNYs4VopfR-xCppNPbctlu_0I',
    appId: '1:745267793428:web:5f170f6a5c71714767e101',
    messagingSenderId: '745267793428',
    projectId: 'prakflutterfirebase-8f942',
    authDomain: 'prakflutterfirebase-8f942.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-8f942.appspot.com',
    measurementId: 'G-199QPGVBX2',
  );
}
