// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCijRQVilRxAPRBWldmFfSbTOHk70QL2Ps',
    appId: '1:625387327144:web:d056fdf5faf5731d8a3c9d',
    messagingSenderId: '625387327144',
    projectId: 'praktikumfultterfirebase',
    authDomain: 'praktikumfultterfirebase.firebaseapp.com',
    storageBucket: 'praktikumfultterfirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb5mY7quZNTQvg_SEnReW00soPooZXcPc',
    appId: '1:625387327144:android:31683731619a562b8a3c9d',
    messagingSenderId: '625387327144',
    projectId: 'praktikumfultterfirebase',
    storageBucket: 'praktikumfultterfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqhRqiwuRNgUulL206zO7z_UI85OrnJuM',
    appId: '1:625387327144:ios:e283ab6a25b4dd398a3c9d',
    messagingSenderId: '625387327144',
    projectId: 'praktikumfultterfirebase',
    storageBucket: 'praktikumfultterfirebase.appspot.com',
    iosBundleId: 'com.example.praktikum09',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqhRqiwuRNgUulL206zO7z_UI85OrnJuM',
    appId: '1:625387327144:ios:e283ab6a25b4dd398a3c9d',
    messagingSenderId: '625387327144',
    projectId: 'praktikumfultterfirebase',
    storageBucket: 'praktikumfultterfirebase.appspot.com',
    iosBundleId: 'com.example.praktikum09',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCijRQVilRxAPRBWldmFfSbTOHk70QL2Ps',
    appId: '1:625387327144:web:adafb194253b96b58a3c9d',
    messagingSenderId: '625387327144',
    projectId: 'praktikumfultterfirebase',
    authDomain: 'praktikumfultterfirebase.firebaseapp.com',
    storageBucket: 'praktikumfultterfirebase.appspot.com',
  );
}
